### ISSUE TITLE
manipulability task and 

### ISSUE THREAD

**Issue by kassasin** [Rhoban/placo-examples#1]
Hello, I'm here again. I have an idea,is it possible to add a task to improve manipulability, because the robot often passes through some singularity ？

**Comment by kassasin** [comment]
I have noticed [Jesse Haviland](https://jhavl.com/) and [Peter Corke](https://petercorke.com/)'s work about [Manipulability Motion Control](https://jhavl.github.io/mmc/).

**Comment by Gregwar** [comment]
Hello, I believe this issue should be moved to the placo repo instead 🙂

**Comment by kassasin** [comment]
> Hello, I believe this issue should be moved to the placo repo instead 🙂 
Sorry my bad.😂

**Comment by kassasin** [comment]
in this [blog,](https://jhavl.github.io/mmc/)they said"The manipulability measure has a complex non-linear relationship with the robot’s joint configuration and in this paper we derive the manipulability Jacobian which directly relates joint velocities to the rate of change of manipulability. Furthermore, we use the manipulability Jacobian within a constrained quadratic program to create an improved resolved-rate motion controller for redundant robots. The resulting real-time controller provides joint velocities which achieve a desired Cartesian end-effector velocity while also maximising the robot’s manipulability"
In their paper,they add a linear term in qp problem in order to maxmise manipulabiliby
![截图_2024-06-12_16-27-35](https://github.com/Rhoban/placo-examples/assets/26887176/02c8c563-3918-4d25-abef-3cedea3bdbe3)
Jm represent manipulabiliby jacobian .
Is it helpful?
